import { ProcessData } from './models';

export const rows: ProcessData[] = [
  {
    id: 1,
    numProcesso: '12345',
    criador: 'João',
    unidadeCriador: 'Departamento A',
    interessado: 'Maria',
    observacao: 'Processo de compra',
    assunto: 'Aquisição de materiais',
    servico: 'Compras',
    valorProcesso: 1500,
    valorExecutado: 1200,
    status: 'Em andamento',
    anexos: [],
  },
  {
    id: 2,
    numProcesso: '54321',
    criador: 'Ana',
    unidadeCriador: 'Departamento B',
    interessado: 'Carlos',
    observacao: 'Processo de aprovação',
    assunto: 'Projeto interno',
    servico: 'Desenvolvimento',
    valorProcesso: 2000,
    valorExecutado: 2000,
    status: 'Concluído',
    anexos: ['anexo3.jpg', 'anexo4.xlsx'],
  },
  {
    id: 3,
    numProcesso: '67890',
    criador: 'Pedro',
    unidadeCriador: 'Departamento C',
    interessado: 'José',
    observacao: 'Processo de contratação',
    assunto: 'Contratação de funcionário',
    servico: 'Recursos Humanos',
    valorProcesso: 3000,
    valorExecutado: 0,
    status: 'Em andamento',
    anexos: ['anexo5.pdf', 'anexo6.doc'],
  },
  {
    id: 4,
    numProcesso: '78900',
    criador: 'Pedro',
    unidadeCriador: 'Departamento C',
    interessado: 'Mariana',
    observacao: 'Processo de contratação',
    assunto: 'Contratação de novo funcionário',
    servico: 'Recursos Humanos',
    valorProcesso: 3000,
    valorExecutado: 2800,
    status: 'Em andamento',
    anexos: ['anexo5.docx', 'anexo6.pdf'],
  },
  {
    id: 5,
    numProcesso: '13579',
    criador: 'Sara',
    unidadeCriador: 'Departamento D',
    interessado: 'Lucas',
    observacao: 'Processo de revisão',
    assunto: 'Revisão de documento técnico',
    servico: 'Qualidade',
    valorProcesso: 1200,
    valorExecutado: 1200,
    status: 'Concluído',
    anexos: ['anexo7.pdf'],
  },
];

export const columns = [
  {
    name: 'numProcesso',
    required: true,
    label: 'Número do Processo',
    align: 'center',
    field: (row: ProcessData) => row.numProcesso,
    format: (val: string) => `${val}`,
    sortable: true,
  },
  {
    name: 'criador',
    align: 'center',
    label: 'Criador',
    field: 'criador',
    sortable: true,
  },
  {
    name: 'unidadeCriador',
    label: 'Unidade do Criador',
    field: 'unidadeCriador',
    sortable: true,
    align: 'center',
  },
  {
    name: 'interessado',
    label: 'Interessado',
    field: 'interessado',
    align: 'center',
  },
  {
    name: 'observacao',
    label: 'Observação',
    field: 'observacao',
    align: 'center',
  },
  { name: 'assunto', label: 'Assunto', field: 'assunto', align: 'center' },
  { name: 'servico', label: 'Serviço', field: 'servico', align: 'center' },
  {
    name: 'valorProcesso',
    label: 'Valor do Processo',
    field: (row: ProcessData) => `R$ ${row.valorProcesso.toFixed(2)}`,
    sortable: true,
    align: 'center',
  },
  {
    name: 'valorExecutado',
    label: 'Valor Executado',
    field: (row: ProcessData) => `R$ ${row.valorExecutado.toFixed(2)}`,
    sortable: true,
    align: 'center',
  },
  { name: 'status', label: 'Status', field: 'status', align: 'center' },
  {
    name: 'anexos',
    label: 'Anexos',
    field: (row: ProcessData) => row.anexos.join(', '),
    sortable: true,
    align: 'center',
  },
];
